USE FURNITURE;

---------#PRODUCT AND CATEGORY#-------

SELECT * FROM PRODUCT
WHERE PRICE > 5000;

SELECT DISTINCT CATEGORYID
FROM PRODUCT;

SELECT * FROM PRODUCT
ORDER BY PRICE ASC;

SELECT CATEGORYID, COUNT(*) FROM PRODUCT
GROUP BY CATEGORYID;

SELECT  * FROM PRODUCT
WHERE STOCK=15;

SELECT * FROM CATEGORY
WHERE CATEGORYID > 2;

SELECT DISTINCT CATEGORYNAME
FROM CATEGORY;

SELECT * FROM CATEGORY
ORDER BY CATEGORYNAME ASC;

---------#SELLER & INVENTORY#----------

SELECT * FROM SELLER
WHERE SELLERID > 205;

SELECT DISTINCT SELLERNAME
FROM SELLER;

SELECT * FROM SELLER
ORDER BY SELLERNAME ASC;

SELECT COUNT(*) AS TOTAL_SELLERS
FROM SELLER;

SELECT * FROM INVENTORY 
 WHERE STATUS = "AVAILABLE";
 
 SELECT * FROM INVENTORY 
 WHERE Status = "UNAVAILABLE";
 
SELECT COUNT(*) AS stock_quantity
FROM INVENTORY;
 
 ----------#ORDERS & DETAILS#------------
 
 SELECT * FROM ORDERSTABLE
WHERE ORDER_STATUS = "Pending";

 SELECT * FROM ORDERSTABLE
WHERE ORDER_STATUS = "Shipped";

SELECT DISTINCT ORDER_STATUS
FROM ORDERSTABLE;

SELECT * FROM ORDERSTABLE
ORDER BY TOTAL_PRICE DESC;

SELECT COUNT(*) AS ORDER_STATUS
FROM ORDERSTABLE;

SELECT * FROM ORDERSTABLE
WHERE TOTAL_PRICE >= 1000;

SELECT * FROM ORDERSDETAIL
WHERE PRODUCT_QUANTITY > 1;

SELECT DISTINCT PRODUCTID
FROM ORDERSDETAIL;

SELECT * FROM ORDERSDETAIL
ORDER BY UNIT_PRICE ASC;

----------#PAYMENT#-----------

SELECT * FROM PAYMENT
WHERE PAYMENT_STATUS = 'Successful';

SELECT * FROM PAYMENT
WHERE PAYMENT_MODE = 'UPI';

SELECT * FROM PAYMENT
WHERE PAYMENT_MODE = 'CARD';

SELECT DISTINCT PAYMENT_MODE
FROM PAYMENT;

SELECT * FROM PAYMENT
ORDER BY PAYMENT_AMOUNT ASC;

SELECT * FROM PAYMENT
ORDER BY PAYMENT_AMOUNT DESC;

----------#REVIEW & RATING#---------

SELECT * FROM REVIEW
WHERE REVIEW_TEXT = 'EXCELLENT';

SELECT * FROM REVIEW
WHERE REVIEW_TEXT = 'GOOD QUALITY';

SELECT * FROM REVIEW
WHERE REVIEW_TEXT = 'GOOD';

SELECT DISTINCT CUSTOMER_NAME
FROM REVIEW;

SELECT * FROM REVIEW
ORDER BY REVIEW_DATE ASC;

SELECT * FROM REVIEW
ORDER BY REVIEW_DATE DESC;

SELECT * FROM RATING
WHERE RATING >= 4;

SELECT DISTINCT RATING
FROM RATING;

SELECT * FROM RATING
ORDER BY RATING ASC;

SELECT * FROM RATING
ORDER BY RATING DESC;

---------------#---------------